### PR TITLE
Generates DISARM as MISP Galaxy + a few fixes

### PR DESCRIPTION
**Pull request by cvandeplas**
Following the conversation in issue #22 I made a script that generates DISARM as MISP Galaxy.
The script uses `generate_DISARM_pages` as library. Thanks for that, it made my life much easier !!!

This pull request also contains a few fixes for the `generate_DISARM_pages` library as it was not working with my panda's version. I also used the opportunity to fix a deprecation warning. 

The result, as can be seen in MISP is :
Screenshot from 2023-12-02 17-56-31

### CODE REVIEW

**Comment by cvandeplas** [comment]
Ok, I had some fun and added more models: actortypes, countermeasures, detections, techniques
image

These are built around the ATT&CK style matrix, with multiple tabs/views:
image

image
image

And so on


The models are also interlinked with relationships bringing lots of opportunities for visualisation:
image

image

Currently issue #24 as there are techniques that have a non-unique name. It'd be great if that could be looked at short-term as this prevents full technical implementation.

**Comment by adulau** [comment]
Any plan for merging this contribution? That would help a lot of MISP users. Thank you.

**Comment by Wachizungu** [comment]
+1, this would help us a lot as well!

**Comment by scampb06** [comment]
Sorry, we've been super stretched. Thanks for all the work here and for fixing issues with the generate script. We just made a framework update.
 To V1.4. Does that affect the MISP Galaxy change you made? Traveling this month. Will try to get to this at month's end.

**Comment by cvandeplas** [comment]
Thank you @scampb06 for the heads up.

v1.4 does not affect the MISP Galaxy structurally, so there are no changes needed in the `generate_DISARM_MISP_galaxy.py` scripts from this Pull Request..   You can find the delta for the MISP Galaxy [here](https://github.com/MISP/misp-galaxy/commit/a04abc9505d80e904f1e4808aa01dd051421d28b). 

Eager to hear your input at the end of the month ! Travel safely.

**Comment by vibenas** [comment]
image

suggested changes: 
1. in name to replace from names like "Countermeasures" to "DISARM Countermeasures", 
2. in description to add particular galaxy name, for example "DISARM Countermeasures is part of DISARM framework designed for describing and understanding disinformation incidents."

That would increase clarity of reading and selecting galaxy items in MISP.

**Comment by cvandeplas** [comment]
Hi @scampb06 , I hope your travel all went smooth. Do you think it'd be possible to get to this in April? Thanks

**Comment by adulau** [comment]
Any news @scampb06 regarding this pull-request? Thank you very much

**Comment by scampb06** [comment]
Finally got to this, sorry it took so long. Thanks for the fixes, Christophe. Hadn't realized it was just a few places you changed the generate pages code, I should have done this months ago. Appreciate everything you and Alexandre do. Stephen.

**Comment by cvandeplas** [comment]
Thank you @scampb06  !

**Pull request merged**
